### ISSUE TITLE
Error when using /ust or right clicking bone

### ISSUE THREAD

**Issue by noiverre** [TWME-TW/UprightSlabTool#4]
Error logs:
```
[22:21:16 INFO]: Server Plugins (6):
[22:21:16 INFO]: Bukkit Plugins:
[22:21:16 INFO]:  - FastAsyncWorldEdit, LuckPerms, PlotSquared, ProtocolLib, UprightSlabTool, Vault
[22:21:18 ERROR]: Could not pass event PlayerInteractEvent to UprightSlabTool v1.2
java.lang.NoClassDefFoundError: Could not initialize class xyz.xenondevs.inventoryaccess.InventoryAccess
        at xyz.xenondevs.invui.item.builder.AbstractItemBuilder.get(AbstractItemBuilder.java:92) ~[UprightSlabTool-1.2.jar:?]
        at xyz.xenondevs.invui.gui.SlotElement$ItemSlotElement.getItemStack(SlotElement.java:34) ~[UprightSlabTool-1.2.jar:?]
        at xyz.xenondevs.invui.window.AbstractWindow.redrawItem(AbstractWindow.java:85) ~[UprightSlabTool-1.2.jar:?]
        at xyz.xenondevs.invui.window.AbstractSingleWindow.initItems(AbstractSingleWindow.java:47) ~[UprightSlabTool-1.2.jar:?]
        at xyz.xenondevs.invui.window.AbstractWindow.open(AbstractWindow.java:298) ~[UprightSlabTool-1.2.jar:?]
        at land.builders.uprightslabtool.gui.slab.GUI.openWindow(GUI.java:51) ~[UprightSlabTool-1.2.jar:?]
        at land.builders.uprightslabtool.listeners.RightClickListener.onLeftClick(RightClickListener.java:45) ~[UprightSlabTool-1.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor117.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[Scissors-API-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[Scissors-API-1.20.1-R0.1-SNAPSHOT.jar:git-Scissors-36]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Scissors-API-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[scissors-1.20.1.jar:git-Scissors-36]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[scissors-1.20.1.jar:git-Scissors-36]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[Scissors-API-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:566) ~[scissors-1.20.1.jar:git-Scissors-36]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:523) ~[scissors-1.20.1.jar:git-Scissors-36]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:517) ~[scissors-1.20.1.jar:git-Scissors-36]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:513) ~[scissors-1.20.1.jar:git-Scissors-36]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:2050) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:32) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemPacket.a(ServerboundUseItemPacket.java:8) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[scissors-1.20.1.jar:git-Scissors-36]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[scissors-1.20.1.jar:git-Scissors-36]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[scissors-1.20.1.jar:git-Scissors-36]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[scissors-1.20.1.jar:git-Scissors-36]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[scissors-1.20.1.jar:git-Scissors-36]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[scissors-1.20.1.jar:git-Scissors-36]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[scissors-1.20.1.jar:git-Scissors-36]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[scissors-1.20.1.jar:git-Scissors-36]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:21:26 INFO]: jwkarsiena issued server command: /ust
[22:21:26 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ust' in plugin UprightSlabTool v1.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[Scissors-API-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[Scissors-API-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1006) ~[scissors-1.20.1.jar:git-Scissors-36]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[scissors-1.20.1.jar:git-Scissors-36]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[scissors-1.20.1.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2339) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2299) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[scissors-1.20.1.jar:git-Scissors-36]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[scissors-1.20.1.jar:git-Scissors-36]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[scissors-1.20.1.jar:git-Scissors-36]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[scissors-1.20.1.jar:git-Scissors-36]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[scissors-1.20.1.jar:git-Scissors-36]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[scissors-1.20.1.jar:git-Scissors-36]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[scissors-1.20.1.jar:git-Scissors-36]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[scissors-1.20.1.jar:git-Scissors-36]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class xyz.xenondevs.inventoryaccess.InventoryAccess
        at xyz.xenondevs.invui.item.builder.AbstractItemBuilder.get(AbstractItemBuilder.java:92) ~[UprightSlabTool-1.2.jar:?]
        at xyz.xenondevs.invui.gui.SlotElement$ItemSlotElement.getItemStack(SlotElement.java:34) ~[UprightSlabTool-1.2.jar:?]
        at xyz.xenondevs.invui.window.AbstractWindow.redrawItem(AbstractWindow.java:85) ~[UprightSlabTool-1.2.jar:?]
        at xyz.xenondevs.invui.window.AbstractSingleWindow.initItems(AbstractSingleWindow.java:47) ~[UprightSlabTool-1.2.jar:?]
        at xyz.xenondevs.invui.window.AbstractWindow.open(AbstractWindow.java:298) ~[UprightSlabTool-1.2.jar:?]
        at land.builders.uprightslabtool.gui.slab.GUI.openWindow(GUI.java:51) ~[UprightSlabTool-1.2.jar:?]
        at land.builders.uprightslabtool.commands.UprightSlabToolCommand.onCommand(UprightSlabToolCommand.java:19) ~[UprightSlabTool-1.2.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[Scissors-API-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 23 more
```

**Comment by TWME-TW** [comment]
I rewrote a similar plugin (but better) a few hours ago, I'll post it later~

**Comment by TWME-TW** [comment]
But you can use the new version first
https://www.spigotmc.org/resources/upright-slab-tool.110269/updates
